// biome-ignore-all lint/performance/noBarrelFile: Public package surface intentionally re-exports the tutorial kit components and templates.

export {
  AccentRule,
  type AccentRuleProps,
} from "./components/accent-rule";
export {
  AnimatedInOut,
  type AnimatedInOutProps,
} from "./components/animated-in-out";
export {
  Arrow,
  type ArrowProps,
  Bracket,
  type BracketProps,
  ConnectorLine,
  type ConnectorLineProps,
  DotMarker,
  type DotMarkerProps,
  FocusFrame,
  type FocusFrameProps,
  FocusRing,
  type FocusRingProps,
  HighlightBar,
  type HighlightBarProps,
  TargetPin,
  type TargetPinProps,
} from "./components/annotation";
export {
  CalloutLabel,
  type CalloutLabelProps,
} from "./components/callout-label";
export { CaptionBand, type CaptionBandProps } from "./components/caption-band";
export {
  AccentCard,
  CommandCard,
  type CommandCardProps,
  FloatingNote,
  InkCard,
  MiniDashboardCard,
  type MiniDashboardCardProps,
  PaperCard,
  type PaperCardProps,
  QuotePanel,
  type QuotePanelProps,
  ResourceCard,
  type ResourceCardProps,
  ResultCard,
  type ResultCardProps,
  ShortcutCard,
  type ShortcutCardProps,
  SuccessPanel,
  WarningPanel,
} from "./components/cards";
export {
  BarPair,
  type BarPairProps,
  BarValue,
  type BarValueProps,
  DeltaArrow,
  type DeltaArrowProps,
  DotPlot,
  type DotPlotProps,
  GaugeArc,
  type GaugeArcProps,
  MetricTile,
  type MetricTileProps,
  MilestoneDot,
  type MilestoneDotProps,
  MiniBarChart,
  type MiniBarChartProps,
  ProgressBar,
  type ProgressBarProps,
  RatioSplit,
  type RatioSplitProps,
  ScoreRing,
  type ScoreRingProps,
  SparkLine,
  type SparkLineProps,
  StackedBar,
  type StackedBarProps,
  TimelineAxis,
  type TimelineAxisProps,
} from "./components/charts";
export { CodeWindow, type CodeWindowProps } from "./components/code-window";
export {
  BeforeAfter,
  type BeforeAfterProps,
  ConceptNode,
  type ConceptNodeProps,
  DecisionFork,
  type DecisionForkProps,
  FormulaStrip,
  type FormulaStripProps,
  IdeaCard,
  type IdeaCardProps,
  QuoteCard,
  type QuoteCardProps,
  StatusStamp,
  type StatusStampProps,
  TimelineStep,
  type TimelineStepProps,
  VersusPair,
  type VersusPairProps,
  WarningMark,
  type WarningMarkProps,
} from "./components/concept";
export { CursorCue, type CursorCueProps } from "./components/cursor-cue";
export {
  DisplayText,
  type DisplayTextProps,
} from "./components/display-text";
export {
  AnswerReveal,
  type AnswerRevealProps,
  CauseEffect,
  type CauseEffectProps,
  Checklist,
  type ChecklistProps,
  ComparisonMatrix,
  type ComparisonMatrixProps,
  ConceptCluster,
  type ConceptClusterProps,
  DefinitionCard,
  type DefinitionCardProps,
  DoDontPair,
  type DoDontPairProps,
  MistakeFixPair,
  type MistakeFixPairProps,
  PrincipleCard,
  type PrincipleCardProps,
  PriorityStack,
  type PriorityStackProps,
  QuestionCard,
  type QuestionCardProps,
  StepStack,
  type StepStackProps,
  TradeoffScale,
  type TradeoffScaleProps,
} from "./components/explanation";
export {
  BranchSplit,
  type BranchSplitProps,
  ConnectorArrow,
  type ConnectorArrowProps,
  ConnectorCurve,
  type ConnectorCurveProps,
  ConnectorElbow,
  type ConnectorElbowProps,
  DecisionNode,
  type DecisionNodeProps,
  DependencyLine,
  type DependencyLineProps,
  FlowGroup,
  type FlowGroupProps,
  FlowNode,
  type FlowNodeProps,
  InputNode,
  LoopArrow,
  type LoopArrowProps,
  MergePoint,
  type MergePointProps,
  NodeBadge,
  type NodeBadgeProps,
  OutputNode,
  ProcessNode,
  type ProcessNodeProps,
  SystemBoundary,
  type SystemBoundaryProps,
} from "./components/flow";
export { Kicker, type KickerProps } from "./components/kicker";
export { LowerThird, type LowerThirdProps } from "./components/lower-third";
export {
  BrowserFrame,
  type BrowserFrameProps,
  DeviceFrame,
  type DeviceFrameProps,
  ImageCallout,
  type ImageCalloutProps,
  ImageCard,
  type ImageCardProps,
  ImageComparison,
  type ImageComparisonProps,
  ImageCutout,
  type ImageCutoutProps,
  LogoNode,
  type LogoNodeProps,
  MaskedImageShape,
  type MaskedImageShapeProps,
  PinnedImage,
  type PinnedImageProps,
  PolaroidFrame,
  type PolaroidFrameProps,
  ScreenshotFrame,
  type ScreenshotFrameProps,
  StampImage,
  type StampImageProps,
  SvgIconFrame,
  type SvgIconFrameProps,
  TerminalFrame,
  type TerminalFrameProps,
  VintagePhotoFrame,
  type VintagePhotoFrameProps,
} from "./components/media";
export { PaperPanel, type PaperPanelProps } from "./components/paper-panel";
export {
  ProgressRail,
  type ProgressRailProps,
} from "./components/progress-rail";
export { SoundCue, type SoundCueProps } from "./components/sound-cue";
export { StatChip, type StatChipProps } from "./components/stat-chip";
export {
  FloatingCard,
  type FloatingCardProps,
  InkSurface,
  type InkSurfaceProps,
  PaperSurface,
  type PaperSurfaceProps,
} from "./components/surface";
export {
  TargetHighlight,
  type TargetHighlightProps,
} from "./components/target-highlight";
export {
  CaptionText,
  type CaptionTextProps,
  Headline,
  type HeadlineProps,
  MonoLabel,
  type MonoLabelProps,
  NumberBadge,
  type NumberBadgeProps,
  ValueChip,
  type ValueChipProps,
} from "./components/text";
export {
  ClickPulse,
  type ClickPulseProps,
  CodeBlock,
  type CodeBlockProps,
  CodeLine,
  type CodeLineProps,
  CursorMark,
  type CursorMarkProps,
  Keycap,
  type KeycapProps,
  ProgressDots,
  type ProgressDotsProps,
  StepPill,
  type StepPillProps,
} from "./components/tutorial";
export type { ComponentDensity, ComponentSize } from "./components/types";
export { cn } from "./lib/cn";
export { enterProgress, exitProgress, UI_EASE } from "./lib/motion";
export { type TutorialSfxCue, tutorialSfxFiles } from "./lib/sfx";
export {
  type OverlayMode,
  type OverlayTone,
  toneBgClass,
  toneBorderClass,
  toneTextClass,
} from "./lib/tones";
export {
  DecisionTreeTemplate,
  type DecisionTreeTemplateProps,
  FlowSequenceTemplate,
  type FlowSequenceTemplateProps,
  ProcessPipelineTemplate,
  type ProcessPipelineTemplateProps,
  SystemMapTemplate,
  type SystemMapTemplateProps,
  TemplateGrid,
  TemplateRow,
  TemplateStack,
  TemplateStage,
  type TemplateStageProps,
  TimelineTemplate,
  type TimelineTemplateProps,
  type TutorialTemplateProps,
} from "./templates/diagram-templates";
