// biome-ignore lint/performance/noBarrelFile: Public package surface intentionally re-exports all tutorial kit atoms and patterns.
export {
  Arrow,
  type ArrowProps,
  Bracket,
  type BracketProps,
  ConnectorLine,
  type ConnectorLineProps,
  DotMarker,
  type DotMarkerProps,
  FocusFrame,
  type FocusFrameProps,
  FocusRing,
  type FocusRingProps,
  HighlightBar,
  type HighlightBarProps,
  TargetPin,
  type TargetPinProps,
} from "./atoms/annotation";
export {
  AccentCard,
  CommandCard,
  type CommandCardProps,
  FloatingNote,
  InkCard,
  MiniDashboardCard,
  type MiniDashboardCardProps,
  PaperCard,
  type PaperCardProps,
  QuotePanel,
  type QuotePanelProps,
  ResourceCard,
  type ResourceCardProps,
  ResultCard,
  type ResultCardProps,
  ShortcutCard,
  type ShortcutCardProps,
  SuccessPanel,
  WarningPanel,
} from "./atoms/cards";
export {
  BarPair,
  type BarPairProps,
  BarValue,
  type BarValueProps,
  DeltaArrow,
  type DeltaArrowProps,
  DotPlot,
  type DotPlotProps,
  GaugeArc,
  type GaugeArcProps,
  MetricTile,
  type MetricTileProps,
  MilestoneDot,
  type MilestoneDotProps,
  MiniBarChart,
  type MiniBarChartProps,
  ProgressBar,
  type ProgressBarProps,
  RatioSplit,
  type RatioSplitProps,
  ScoreRing,
  type ScoreRingProps,
  SparkLine,
  type SparkLineProps,
  StackedBar,
  type StackedBarProps,
  TimelineAxis,
  type TimelineAxisProps,
} from "./atoms/charts";
export {
  BeforeAfter,
  type BeforeAfterProps,
  ConceptNode,
  type ConceptNodeProps,
  DecisionFork,
  type DecisionForkProps,
  FormulaStrip,
  type FormulaStripProps,
  IdeaCard,
  type IdeaCardProps,
  QuoteCard,
  type QuoteCardProps,
  StatusStamp,
  type StatusStampProps,
  TimelineStep,
  type TimelineStepProps,
  VersusPair,
  type VersusPairProps,
  WarningMark,
  type WarningMarkProps,
} from "./atoms/concept";
export {
  AnswerReveal,
  type AnswerRevealProps,
  CauseEffect,
  type CauseEffectProps,
  ChecklistAtom,
  type ChecklistAtomProps,
  ComparisonMatrix,
  type ComparisonMatrixProps,
  ConceptCluster,
  type ConceptClusterProps,
  DefinitionCard,
  type DefinitionCardProps,
  DoDontPair,
  type DoDontPairProps,
  MistakeFixPair,
  type MistakeFixPairProps,
  PrincipleCard,
  type PrincipleCardProps,
  PriorityStack,
  type PriorityStackProps,
  QuestionCard,
  type QuestionCardProps,
  StepStack,
  type StepStackProps,
  TradeoffScale,
  type TradeoffScaleProps,
} from "./atoms/explanation";
export {
  BranchSplit,
  type BranchSplitProps,
  ConnectorArrow,
  type ConnectorArrowProps,
  ConnectorCurve,
  type ConnectorCurveProps,
  ConnectorElbow,
  type ConnectorElbowProps,
  DecisionNode,
  type DecisionNodeProps,
  DependencyLine,
  type DependencyLineProps,
  FlowGroup,
  type FlowGroupProps,
  FlowNode,
  type FlowNodeProps,
  InputNode,
  LoopArrow,
  type LoopArrowProps,
  MergePoint,
  type MergePointProps,
  NodeBadge,
  type NodeBadgeProps,
  OutputNode,
  ProcessNode,
  type ProcessNodeProps,
  SystemBoundary,
  type SystemBoundaryProps,
} from "./atoms/flow";
export {
  BrowserFrame,
  type BrowserFrameProps,
  DeviceFrame,
  type DeviceFrameProps,
  ImageCallout,
  type ImageCalloutProps,
  ImageCard,
  type ImageCardProps,
  ImageComparison,
  type ImageComparisonProps,
  ImageCutout,
  type ImageCutoutProps,
  LogoNode,
  type LogoNodeProps,
  MaskedImageShape,
  type MaskedImageShapeProps,
  PinnedImage,
  type PinnedImageProps,
  PolaroidFrame,
  type PolaroidFrameProps,
  ScreenshotFrame,
  type ScreenshotFrameProps,
  StampImage,
  type StampImageProps,
  SvgIconFrame,
  type SvgIconFrameProps,
  TerminalFrame,
  type TerminalFrameProps,
  VintagePhotoFrame,
  type VintagePhotoFrameProps,
} from "./atoms/media";
export {
  FloatingCard,
  type FloatingCardProps,
  InkSurface,
  type InkSurfaceProps,
  MetadataStrip,
  type MetadataStripProps,
  PaperSurface,
  type PaperSurfaceProps,
} from "./atoms/surface";
export {
  CaptionText,
  type CaptionTextProps,
  Headline,
  type HeadlineProps,
  MonoLabel,
  type MonoLabelProps,
  NumberBadge,
  type NumberBadgeProps,
  ValueChip,
  type ValueChipProps,
} from "./atoms/text";
export {
  ClickPulse,
  type ClickPulseProps,
  CodeBlock,
  type CodeBlockProps,
  CodeLine,
  type CodeLineProps,
  CursorMark,
  type CursorMarkProps,
  Keycap,
  type KeycapProps,
  ProgressDots,
  type ProgressDotsProps,
  StepPill,
  type StepPillProps,
} from "./atoms/tutorial";
export type { AtomDensity, AtomSize } from "./atoms/types";
export { CalloutLabel, type CalloutLabelProps } from "./blocks/callout-label";
export { CaptionBand, type CaptionBandProps } from "./blocks/caption-band";
export { CodeWindow, type CodeWindowProps } from "./blocks/code-window";
export { CursorCue, type CursorCueProps } from "./blocks/cursor-cue";
export { LowerThird, type LowerThirdProps } from "./blocks/lower-third";
export { ProgressRail, type ProgressRailProps } from "./blocks/progress-rail";
export { StatChip, type StatChipProps } from "./blocks/stat-chip";
export {
  TargetHighlight,
  type TargetHighlightProps,
} from "./blocks/target-highlight";
export { cn } from "./lib/cn";
export { enterProgress, exitProgress, UI_EASE } from "./lib/motion";
export { type TutorialSfxCue, tutorialSfxFiles } from "./lib/sfx";
export {
  type OverlayMode,
  type OverlayTone,
  toneBgClass,
  toneBorderClass,
  toneTextClass,
} from "./lib/tones";
export {
  BeforeAfterDiagram,
  BranchingDecisionFlow,
  ChartCallout,
  ChartTrendPattern,
  CodePlusResult,
  ComparisonOverlay,
  ImageWithConceptNodes,
  InputProcessOutput,
  LinearFlowDiagram,
  ModelPipeline,
  NarrationSupportCard,
  ProblemSolutionResult,
  ScreenshotWithAnnotations,
  ThreeStepExplainer,
  TimelineExplainer,
  ToolchainFlow,
  type TutorialPatternProps,
} from "./patterns/diagram-patterns";
export {
  AccentRule,
  type AccentRuleProps,
} from "./primitives/accent-rule";
export {
  AnimatedInOut,
  type AnimatedInOutProps,
} from "./primitives/animated-in-out";
export {
  DisplayText,
  type DisplayTextProps,
} from "./primitives/display-text";
export { Kicker, type KickerProps } from "./primitives/kicker";
export { MetaStrip, type MetaStripProps } from "./primitives/meta-strip";
export {
  OverlayStage,
  type OverlayStageProps,
} from "./primitives/overlay-stage";
export { PaperPanel, type PaperPanelProps } from "./primitives/paper-panel";
export { SideRail, type SideRailProps } from "./primitives/side-rail";
export { SoundCue, type SoundCueProps } from "./primitives/sound-cue";
